interface GroundData {
  id: number;
  positionX: number;
  positionZ: number;
  positionY: number;
  isActive: boolean;
  isWall: boolean;
}
interface State {
  groundDataList: GroundData[];
}
export const useModularGroundStore = defineStore("ModuleStore", {
  state: (): State => {
    return {
      groundDataList: [
        {
          id: 1,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: true,
        },
        {
          id: 2,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: true,
        },
        {
          id: 3,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: true,
        },
        {
          id: 4,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: true,
        },
        {
          id: 5,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: true,
        },
        {
          id: 6,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: true,
        },
        {
          id: 7,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: true,
        },
        {
          id: 8,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: true,
        },
        {
          id: 9,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: true,
        },
        {
          id: 10,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: true,
        },
        {
          id: 11,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: true,
        },
        {
          id: 12,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: true,
        },
        {
          id: 13,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: true,
        },
        {
          id: 14,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: true,
        },
        {
          id: 15,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: true,
        },
        {
          id: 16,
          positionX: -105,
          positionZ: -90,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 17,
          positionX: -90,
          positionZ: -90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 18,
          positionX: -75,
          positionZ: -90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },

        {
          id: 19,
          positionX: -60,
          positionZ: -90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },

        {
          id: 20,
          positionX: -45,
          positionZ: -90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 21,
          positionX: -30,
          positionZ: -90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 22,
          positionX: -15,
          positionZ: -90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 23,
          positionX: 0,
          positionZ: -90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 24,
          positionX: 15,
          positionZ: -90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 25,
          positionX: 30,
          positionZ: -90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 26,
          positionX: 45,
          positionZ: -90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 27,
          positionX: 60,
          positionZ: -90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 28,
          positionX: 75,
          positionZ: -90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 29,
          positionX: 90,
          positionZ: -90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 30,
          positionX: 105,
          positionZ: -90,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 31,
          positionX: -105,
          positionZ: -75,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 32,
          positionX: -90,
          positionZ: -75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 33,
          positionX: -75,
          positionZ: -75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 34,
          positionX: -60,
          positionZ: -75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 35,
          positionX: -45,
          positionZ: -75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 36,
          positionX: -30,
          positionZ: -75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 37,
          positionX: -15,
          positionZ: -75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 38,
          positionX: 0,
          positionZ: -75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 39,
          positionX: 15,
          positionZ: -75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 40,
          positionX: 30,
          positionZ: -75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 41,
          positionX: 45,
          positionZ: -75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 42,
          positionX: 60,
          positionZ: -75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 43,
          positionX: 75,
          positionZ: -75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 44,
          positionX: 90,
          positionZ: -75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 45,
          positionX: 105,
          positionZ: -75,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 46,
          positionX: -105,
          positionZ: -60,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 47,
          positionX: -90,
          positionZ: -60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 48,
          positionX: -75,
          positionZ: -60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 49,
          positionX: -60,
          positionZ: -60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 50,
          positionX: -45,
          positionZ: -60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 51,
          positionX: -30,
          positionZ: -60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 52,
          positionX: -15,
          positionZ: -60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 53,
          positionX: 0,
          positionZ: -60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 54,
          positionX: 15,
          positionZ: -60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 55,
          positionX: 30,
          positionZ: -60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 56,
          positionX: 45,
          positionZ: -60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 57,
          positionX: 60,
          positionZ: -60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 58,
          positionX: 75,
          positionZ: -60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 59,
          positionX: 90,
          positionZ: -60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 60,
          positionX: 105,
          positionZ: -60,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 61,
          positionX: -105,
          positionZ: -45,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 62,
          positionX: -90,
          positionZ: -45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 63,
          positionX: -75,
          positionZ: -45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 64,
          positionX: -60,
          positionZ: -45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 65,
          positionX: -45,
          positionZ: -45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 66,
          positionX: -30,
          positionZ: -45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 67,
          positionX: -15,
          positionZ: -45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 68,
          positionX: 0,
          positionZ: -45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 69,
          positionX: 15,
          positionZ: -45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 70,
          positionX: 30,
          positionZ: -45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 71,
          positionX: 45,
          positionZ: -45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 72,
          positionX: 60,
          positionZ: -45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 73,
          positionX: 75,
          positionZ: -45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 74,
          positionX: 90,
          positionZ: -45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 75,
          positionX: 105,
          positionZ: -45,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 76,
          positionX: -105,
          positionZ: -30,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 77,
          positionX: -90,
          positionZ: -30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 78,
          positionX: -75,
          positionZ: -30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 79,
          positionX: -60,
          positionZ: -30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 80,
          positionX: -45,
          positionZ: -30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 81,
          positionX: -30,
          positionZ: -30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 82,
          positionX: -15,
          positionZ: -30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 83,
          positionX: 0,
          positionZ: -30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 84,
          positionX: 15,
          positionZ: -30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 85,
          positionX: 30,
          positionZ: -30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 86,
          positionX: 45,
          positionZ: -30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 87,
          positionX: 60,
          positionZ: -30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 88,
          positionX: 75,
          positionZ: -30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 89,
          positionX: 90,
          positionZ: -30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 90,
          positionX: 105,
          positionZ: -30,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 91,
          positionX: -105,
          positionZ: -15,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 92,
          positionX: -90,
          positionZ: -15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 93,
          positionX: -75,
          positionZ: -15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 94,
          positionX: -60,
          positionZ: -15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 95,
          positionX: -45,
          positionZ: -15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 96,
          positionX: -30,
          positionZ: -15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 97,
          positionX: -15,
          positionZ: -15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 98,
          positionX: 0,
          positionZ: -15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 99,
          positionX: 15,
          positionZ: -15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 100,
          positionX: 30,
          positionZ: -15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 101,
          positionX: 45,
          positionZ: -15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 102,
          positionX: 60,
          positionZ: -15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 103,
          positionX: 75,
          positionZ: -15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 104,
          positionX: 90,
          positionZ: -15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 105,
          positionX: 105,
          positionZ: -15,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 106,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: true,
        },
        {
          id: 107,
          positionX: -90,
          positionZ: 0,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 108,
          positionX: -75,
          positionZ: 0,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 109,
          positionX: -60,
          positionZ: 0,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 110,
          positionX: -45,
          positionZ: 0,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 111,
          positionX: -30,
          positionZ: 0,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 112,
          positionX: -15,
          positionZ: 0,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 113,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 114,
          positionX: 15,
          positionZ: 0,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 115,
          positionX: 30,
          positionZ: 0,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 116,
          positionX: 45,
          positionZ: 0,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 117,
          positionX: 60,
          positionZ: 0,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 118,
          positionX: 75,
          positionZ: 0,
          positionY: 0,
          isActive: true,
          isWall: false,
        },

        {
          id: 119,
          positionX: 90,
          positionZ: 0,
          positionY: 0,
          isActive: true,
          isWall: false,
        },

        {
          id: 120,
          positionX: 105,
          positionZ: 0,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 121,
          positionX: -105,
          positionZ: 15,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 122,
          positionX: -90,
          positionZ: 15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 123,
          positionX: -75,
          positionZ: 15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 124,
          positionX: -60,
          positionZ: 15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 125,
          positionX: -45,
          positionZ: 15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 126,
          positionX: -30,
          positionZ: 15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 127,
          positionX: -15,
          positionZ: 15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 128,
          positionX: 0,
          positionZ: 15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 129,
          positionX: 15,
          positionZ: 15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 130,
          positionX: 30,
          positionZ: 15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 131,
          positionX: 45,
          positionZ: 15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 132,
          positionX: 60,
          positionZ: 15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 133,
          positionX: 75,
          positionZ: 15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 134,
          positionX: 90,
          positionZ: 15,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 135,
          positionX: 105,
          positionZ: 15,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 136,
          positionX: -105,
          positionZ: 30,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 137,
          positionX: -90,
          positionZ: 30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 138,
          positionX: -75,
          positionZ: 30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 139,
          positionX: -60,
          positionZ: 30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 140,
          positionX: -45,
          positionZ: 30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 141,
          positionX: -30,
          positionZ: 30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 142,
          positionX: -15,
          positionZ: 30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 143,
          positionX: 0,
          positionZ: 30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 144,
          positionX: 15,
          positionZ: 30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 145,
          positionX: 30,
          positionZ: 30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 146,
          positionX: 45,
          positionZ: 30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 147,
          positionX: 60,
          positionZ: 30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 148,
          positionX: 75,
          positionZ: 30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 149,
          positionX: 90,
          positionZ: 30,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 150,
          positionX: 105,
          positionZ: 30,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 151,
          positionX: -105,
          positionZ: 45,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 152,
          positionX: -90,
          positionZ: 45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 153,
          positionX: -75,
          positionZ: 45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 154,
          positionX: -60,
          positionZ: 45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 155,
          positionX: -45,
          positionZ: 45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 156,
          positionX: -30,
          positionZ: 45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 157,
          positionX: -15,
          positionZ: 45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 158,
          positionX: 0,
          positionZ: 45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 159,
          positionX: 15,
          positionZ: 45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 160,
          positionX: 30,
          positionZ: 45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 161,
          positionX: 45,
          positionZ: 45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 162,
          positionX: 60,
          positionZ: 45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 163,
          positionX: 75,
          positionZ: 45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 164,
          positionX: 90,
          positionZ: 45,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 165,
          positionX: 105,
          positionZ: 45,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 166,
          positionX: -105,
          positionZ: 60,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 167,
          positionX: -90,
          positionZ: 60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 168,
          positionX: -75,
          positionZ: 60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 169,
          positionX: -60,
          positionZ: 60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 170,
          positionX: -45,
          positionZ: 60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 171,
          positionX: -30,
          positionZ: 60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 172,
          positionX: -15,
          positionZ: 60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 173,
          positionX: 0,
          positionZ: 60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 174,
          positionX: 15,
          positionZ: 60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 175,
          positionX: 30,
          positionZ: 60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 176,
          positionX: 45,
          positionZ: 60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 177,
          positionX: 60,
          positionZ: 60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 178,
          positionX: 75,
          positionZ: 60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 179,
          positionX: 90,
          positionZ: 60,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 180,
          positionX: 105,
          positionZ: 60,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 181,
          positionX: -105,
          positionZ: 75,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 182,
          positionX: -90,
          positionZ: 75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 183,
          positionX: -75,
          positionZ: 75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 184,
          positionX: -60,
          positionZ: 75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 185,
          positionX: -45,
          positionZ: 75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 186,
          positionX: -30,
          positionZ: 75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 187,
          positionX: -15,
          positionZ: 75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 188,
          positionX: 0,
          positionZ: 75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 189,
          positionX: 15,
          positionZ: 75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 190,
          positionX: 30,
          positionZ: 75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 191,
          positionX: 45,
          positionZ: 75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 192,
          positionX: 60,
          positionZ: 75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 193,
          positionX: 75,
          positionZ: 75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 194,
          positionX: 90,
          positionZ: 75,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 195,
          positionX: 105,
          positionZ: 75,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 196,
          positionX: -105,
          positionZ: 90,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 197,
          positionX: -90,
          positionZ: 90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 198,
          positionX: -75,
          positionZ: 90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 199,
          positionX: -60,
          positionZ: 90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 200,
          positionX: -45,
          positionZ: 90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 201,
          positionX: -30,
          positionZ: 90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 202,
          positionX: -15,
          positionZ: 90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 203,
          positionX: 0,
          positionZ: 90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 204,
          positionX: 15,
          positionZ: 90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 205,
          positionX: 30,
          positionZ: 90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 206,
          positionX: 45,
          positionZ: 90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 207,
          positionX: 60,
          positionZ: 90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 208,
          positionX: 75,
          positionZ: 90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 209,
          positionX: 90,
          positionZ: 90,
          positionY: 0,
          isActive: true,
          isWall: false,
        },
        {
          id: 210,
          positionX: 105,
          positionZ: 90,
          positionY: 0,
          isActive: true,
          isWall: true,
        },
        {
          id: 211,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: true,
        },
        {
          id: 212,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: false,
        },
        {
          id: 213,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: false,
        },
        {
          id: 214,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: false,
        },
        {
          id: 215,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: false,
        },
        {
          id: 216,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: false,
        },
        {
          id: 217,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: false,
        },
        {
          id: 218,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: false,
        },

        {
          id: 219,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: false,
        },

        {
          id: 220,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: false,
        },
        {
          id: 221,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: false,
        },
        {
          id: 222,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: false,
        },
        {
          id: 223,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: false,
        },
        {
          id: 224,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: false,
        },
        {
          id: 225,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
          isWall: true,
        },
      ],
    };
  },
  getters: {
    activeModularList: (state) =>
      state.groundDataList.filter((data) => data.isActive && !data.isWall),
  },
  actions: {
    //   setCharacterModel(data: any) {
    //     this.characterModel = data;
    //   },
  },
});
