interface GroundData {
  index: number;
  positionX: number;
  positionZ: number;
  positionY: number;
  isActive: boolean;
}
interface State {
  groundData: GroundData[];
}
export const useModularGroundStore = defineStore("ModuleStore", {
  state: (): State => {
    return {
      groundData: [
        {
          index: 1,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 2,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 3,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 4,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 5,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 6,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 7,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 8,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 9,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 10,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 11,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 12,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 13,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 14,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 15,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 16,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 17,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 18,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },

        {
          index: 19,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },

        {
          index: 20,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 21,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 22,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 23,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 24,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 25,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 26,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 27,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 28,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 29,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 30,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 31,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 32,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 33,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 34,
          positionX: -30,
          positionZ: -30,
          positionY: 0,
          isActive: true,
        },
        {
          index: 35,
          positionX: -10,
          positionZ: -30,
          positionY: 0,
          isActive: true,
        },
        {
          index: 36,
          positionX: 10,
          positionZ: -30,
          positionY: 0,
          isActive: true,
        },
        {
          index: 37,
          positionX: 30,
          positionZ: -30,
          positionY: 0,
          isActive: true,
        },
        {
          index: 38,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 39,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 40,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 41,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 42,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 43,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 44,
          positionX: -30,
          positionZ: -10,
          positionY: 0,
          isActive: true,
        },
        {
          index: 45,
          positionX: -10,
          positionZ: -10,
          positionY: 0,
          isActive: true,
        },
        {
          index: 46,
          positionX: 10,
          positionZ: -10,
          positionY: 0,
          isActive: true,
        },
        {
          index: 47,
          positionX: 30,
          positionZ: -10,
          positionY: 0,
          isActive: true,
        },
        {
          index: 48,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 49,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 50,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 51,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 52,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 53,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 54,
          positionX: -30,
          positionZ: 10,
          positionY: 0,
          isActive: true,
        },
        {
          index: 55,
          positionX: -10,
          positionZ: 10,
          positionY: 0,
          isActive: true,
        },
        {
          index: 56,
          positionX: 10,
          positionZ: 10,
          positionY: 0,
          isActive: true,
        },
        {
          index: 57,
          positionX: 30,
          positionZ: 10,
          positionY: 0,
          isActive: true,
        },
        {
          index: 58,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 59,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 60,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 61,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 62,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 63,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 64,
          positionX: -30,
          positionZ: 30,
          positionY: 0,
          isActive: true,
        },
        {
          index: 65,
          positionX: -10,
          positionZ: 30,
          positionY: 0,
          isActive: true,
        },
        {
          index: 66,
          positionX: 10,
          positionZ: 30,
          positionY: 0,
          isActive: true,
        },
        {
          index: 67,
          positionX: 30,
          positionZ: 30,
          positionY: 0,
          isActive: true,
        },
        {
          index: 68,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 69,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 70,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 71,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 72,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 73,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 74,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 75,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 76,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 77,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 78,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 79,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 80,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 81,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 82,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 83,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 84,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 85,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 86,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 87,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 88,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 89,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 90,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 91,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 92,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 93,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 94,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 95,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 96,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 97,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 98,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 99,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
        {
          index: 100,
          positionX: 0,
          positionZ: 0,
          positionY: 0,
          isActive: false,
        },
      ],
    };
  },
  getters: {
    activeModularList: (state) =>
      state.groundData.filter((data) => data.isActive),
  },
  actions: {
    //   setCharacterModel(data: any) {
    //     this.characterModel = data;
    //   },
  },
});
